#!/bin/bash
cd /app

if [ -f config/pre-service.sh ]
then
  source config/pre-service.sh
fi

if [ $SERVICE_MODE = "background" ]
then
  sidekiq
else
  nginx &
  unicorn -c /etc/unicorn/unicorn.rb
fi

