#!/bin/bash
cd /app

if [ -f config/pre-service.sh ]
then
  source config/pre-service.sh
fi

if [ $SERVICE_MODE = "background" ]
then
  bundle exec sidekiq
else
  nginx &
  bundle exec puma -C /etc/puma/puma.rb
fi

